[package]
name = "trait"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
ntex = "0.1.17"
ntex-rt = "0.1.1"
ntex_ratelimiter = { path = "../../" }
tokio = "0.2.20"
